baseURL = ''
[languages]
  [languages.en]
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1
[languages]
  [languages.fa]
    languageCode = 'fa-IR'
    languageDirection = 'rtl'
    languageName = 'Farsi'
    weight = 1
title = 'Mustafa Tayefi'
theme = 'PaperMod'
min_version = '0.125.7'